In [1]:
import numpy as np
print(np.__version__)

1.19.5


In [2]:
import pandas as pd
print(pd.__version__)

1.2.0


In [3]:
df = pd.read_csv('data.csv')

In [4]:
df.head()

Make       Model  Year             Engine Fuel Type  Engine HP  \
0  BMW  1 Series M  2011  premium unleaded (required)      335.0   
1  BMW    1 Series  2011  premium unleaded (required)      300.0   
2  BMW    1 Series  2011  premium unleaded (required)      300.0   
3  BMW    1 Series  2011  premium unleaded (required)      230.0   
4  BMW    1 Series  2011  premium unleaded (required)      230.0   

   Engine Cylinders Transmission Type     Driven_Wheels  Number of Doors  \
0               6.0            MANUAL  rear wheel drive              2.0   
1               6.0            MANUAL  rear wheel drive              2.0   
2               6.0            MANUAL  rear wheel drive              2.0   
3               6.0            MANUAL  rear wheel drive              2.0   
4               6.0            MANUAL  rear wheel drive              2.0   

                         Market Category Vehicle Size Vehicle Style  \
0  Factory Tuner,Luxury,High-Performance      Compact         Coupe   
1                     Luxury,Performance      Compact   Convertible   
2                Luxury,High-Performance      Compact         Coupe   
3                     Luxury,Performance      Compact         Coupe   
4                                 Luxury      Compact   Convertible   

   highway MPG  city mpg  Popularity   MSRP  
0           26        19        3916  46135  
1           28        19        3916  40650  
2           28        20        3916  36350  
3           28        18        3916  29450  
4           28        18        3916  34500

In [7]:
df[df['Make'] == 'BMW']['MSRP'].mean()

61546.76347305389

In [9]:
df[df['Year'] >= 2015]['Engine HP'].isnull().sum()

51

In [13]:
mean_before = round(df['Engine HP'].mean())

In [15]:
df_hpfill = df.copy()
df_hpfill['Engine HP'].fillna(mean_before, inplace = True)
print(df_hpfill['Engine HP'].isnull().sum(), df['Engine HP'].isnull().sum())

0 69


In [16]:
mean_after = round(df_hpfill['Engine HP'].mean())
print(mean_before, mean_after)

249 249


In [19]:
df_hpfill.Make.unique()

array(['BMW', 'Audi', 'FIAT', 'Mercedes-Benz', 'Chrysler', 'Nissan',
       'Volvo', 'Mazda', 'Mitsubishi', 'Ferrari', 'Alfa Romeo', 'Toyota',
       'McLaren', 'Maybach', 'Pontiac', 'Porsche', 'Saab', 'GMC',
       'Hyundai', 'Plymouth', 'Honda', 'Oldsmobile', 'Suzuki', 'Ford',
       'Cadillac', 'Kia', 'Bentley', 'Chevrolet', 'Dodge', 'Lamborghini',
       'Lincoln', 'Subaru', 'Volkswagen', 'Spyker', 'Buick', 'Acura',
       'Rolls-Royce', 'Maserati', 'Lexus', 'Aston Martin', 'Land Rover',
       'Lotus', 'Infiniti', 'Scion', 'Genesis', 'HUMMER', 'Tesla',
       'Bugatti'], dtype=object)

In [20]:
df_rollroyce = df_hpfill[df_hpfill['Make']=='Rolls-Royce']
df_rollroyce = df_rollroyce[["Engine HP", "Engine Cylinders", "highway MPG"]]
df_rollroyce.drop_duplicates(inplace=True)
df_rollroyce

Engine HP  Engine Cylinders  highway MPG
2921       325.0               8.0           15
3505       563.0              12.0           19
5275       563.0              12.0           21
5279       563.0              12.0           20
7443       322.0              12.0           15
7553       453.0              12.0           19
11448      624.0              12.0           21

In [21]:
X = np.array(df_rollroyce)
print(X)

[[325.   8.  15.]
 [563.  12.  19.]
 [563.  12.  21.]
 [563.  12.  20.]
 [322.  12.  15.]
 [453.  12.  19.]
 [624.  12.  21.]]


In [22]:
TX = X.T
print(TX)

[[325. 563. 563. 563. 322. 453. 624.]
 [  8.  12.  12.  12.  12.  12.  12.]
 [ 15.  19.  21.  20.  15.  19.  21.]]


In [25]:
XTX = np.matmul(X,TX)
print(XTX)

[[105914. 183356. 183386. 183371. 104971. 147606. 203211.]
 [183356. 317474. 317512. 317493. 181715. 255544. 351855.]
 [183386. 317512. 317554. 317533. 181745. 255582. 351897.]
 [183371. 317493. 317533. 317513. 181730. 255563. 351876.]
 [104971. 181715. 181745. 181730. 104053. 146295. 201387.]
 [147606. 255544. 255582. 255563. 146295. 205714. 283215.]
 [203211. 351855. 351897. 351876. 201387. 283215. 389961.]]


In [27]:
XTX_inv =  np.linalg.inv(XTX) 
print(XTX_inv)

[[-1.17692099e+08 -1.52663979e+10 -2.18643478e+10  9.87667349e+09
   3.92546916e+08  9.09157436e+09  1.78484123e+10]
 [ 8.93682480e+08 -6.04247044e+09 -3.20165591e+10  2.84987651e+08
  -5.39140092e+09  2.25210206e+10  2.00486338e+10]
 [-7.72687444e+09 -8.71098714e+09  2.13199250e+10 -7.83814164e+09
   5.15149355e+09 -6.68785992e+09  1.91681981e+09]
 [-4.27931933e+09  3.06576812e+09  7.52506722e+09  1.49603739e+10
  -4.73949961e+09  1.53288406e+09 -1.94917142e+10]
 [-2.30129737e+09 -1.24944503e+10  3.69154214e+09  4.11008733e+09
   5.17866104e+09 -6.24722516e+09  7.29558321e+09]
 [ 8.09102325e+09  3.43597384e+10  6.24722516e+09 -1.51570999e+10
  -7.57855893e+09  0.00000000e+00 -2.32653202e+10]
 [ 5.40124681e+09 -0.00000000e+00  7.80903145e+09 -2.94465640e+09
   7.11760693e+09 -1.71798692e+10  1.59705600e+09]]


In [29]:
sum(sum(XTX_inv))

-13076899.844997406